GET http://localhost:3000/api/v1/products/1245

# POST http://localhost:3000/api/v1/products

# {
#     "name": "New Product",
#     "price": 1209,
#     "image": "https://loremflickr.com/640/480"
#   },
